parent=keycloak.v2
import=common/keycloak

styles=css/login.css css/ballast-lane-board.css
scripts=js/navbar.js

kcHtmlClass=login-pf
kcLoginClass=login-pf-page
kcContentWrapperClass=row
kcHeaderClass=login-pf-page-header
kcFeedbackAreaClass=col-md-12
kcFormAreaClass=col-md-12
