events {}

http {
    resolver 127.0.0.11 ipv6=off;

    map $http_host $forwarded_port {
        ~^[^:]+:(\d+)$ $1;
        default 80;
    }

    server {
        listen 80;
        server_name _;

        location ~* ^/(realms|resources|admin|js)(/|$) {
            set $keycloak_upstream http://keycloak:8080;
            proxy_pass         $keycloak_upstream;
            proxy_set_header   Host              $http_host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto http;
            proxy_set_header   X-Forwarded-Host  $http_host;
            proxy_set_header   X-Forwarded-Port  $forwarded_port;
        }

        location / {
            set $api_upstream http://api:8080;
            proxy_pass         $api_upstream;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto http;
        }
    }
}
