### YamlMime:ManagedReference
items:
- uid: BallastLaneBoard.Application.TaskManagement.ITaskUoW
  commentId: T:BallastLaneBoard.Application.TaskManagement.ITaskUoW
  id: ITaskUoW
  parent: BallastLaneBoard.Application.TaskManagement
  children:
  - BallastLaneBoard.Application.TaskManagement.ITaskUoW.Tasks
  langs:
  - csharp
  - vb
  name: ITaskUoW
  nameWithType: ITaskUoW
  fullName: BallastLaneBoard.Application.TaskManagement.ITaskUoW
  type: Interface
  source:
    remote:
      path: src/BallastLaneBoard.Application/TaskManagement/ITaskUoW.cs
      branch: master
      repo: https://github.com/cleberMargarida/ballast-lane-board.git
    id: ITaskUoW
    path: ../src/BallastLaneBoard.Application/TaskManagement/ITaskUoW.cs
    startLine: 5
  assemblies:
  - BallastLaneBoard.Application
  namespace: BallastLaneBoard.Application.TaskManagement
  syntax:
    content: 'public interface ITaskUoW : IUnitOfWork'
    content.vb: Public Interface ITaskUoW Inherits IUnitOfWork
  inheritedMembers:
  - BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit
  - BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit(System.Threading.CancellationToken)
- uid: BallastLaneBoard.Application.TaskManagement.ITaskUoW.Tasks
  commentId: P:BallastLaneBoard.Application.TaskManagement.ITaskUoW.Tasks
  id: Tasks
  parent: BallastLaneBoard.Application.TaskManagement.ITaskUoW
  langs:
  - csharp
  - vb
  name: Tasks
  nameWithType: ITaskUoW.Tasks
  fullName: BallastLaneBoard.Application.TaskManagement.ITaskUoW.Tasks
  type: Property
  source:
    remote:
      path: src/BallastLaneBoard.Application/TaskManagement/ITaskUoW.cs
      branch: master
      repo: https://github.com/cleberMargarida/ballast-lane-board.git
    id: Tasks
    path: ../src/BallastLaneBoard.Application/TaskManagement/ITaskUoW.cs
    startLine: 7
  assemblies:
  - BallastLaneBoard.Application
  namespace: BallastLaneBoard.Application.TaskManagement
  syntax:
    content: IRepository<TaskItem> Tasks { get; }
    parameters: []
    return:
      type: BallastLaneBoard.Application.Abstractions.IRepository{BallastLaneBoard.Domain.TaskManagement.TaskItem}
    content.vb: ReadOnly Property Tasks As IRepository(Of TaskItem)
  overload: BallastLaneBoard.Application.TaskManagement.ITaskUoW.Tasks*
references:
- uid: BallastLaneBoard.Application.TaskManagement
  commentId: N:BallastLaneBoard.Application.TaskManagement
  href: BallastLaneBoard.html
  name: BallastLaneBoard.Application.TaskManagement
  nameWithType: BallastLaneBoard.Application.TaskManagement
  fullName: BallastLaneBoard.Application.TaskManagement
  spec.csharp:
  - uid: BallastLaneBoard
    name: BallastLaneBoard
    href: BallastLaneBoard.html
  - name: .
  - uid: BallastLaneBoard.Application
    name: Application
    href: BallastLaneBoard.Application.html
  - name: .
  - uid: BallastLaneBoard.Application.TaskManagement
    name: TaskManagement
    href: BallastLaneBoard.Application.TaskManagement.html
  spec.vb:
  - uid: BallastLaneBoard
    name: BallastLaneBoard
    href: BallastLaneBoard.html
  - name: .
  - uid: BallastLaneBoard.Application
    name: Application
    href: BallastLaneBoard.Application.html
  - name: .
  - uid: BallastLaneBoard.Application.TaskManagement
    name: TaskManagement
    href: BallastLaneBoard.Application.TaskManagement.html
- uid: BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit
  commentId: M:BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit
  parent: BallastLaneBoard.Application.Abstractions.IUnitOfWork
  href: BallastLaneBoard.Application.Abstractions.IUnitOfWork.html#BallastLaneBoard_Application_Abstractions_IUnitOfWork_Commit
  name: Commit()
  nameWithType: IUnitOfWork.Commit()
  fullName: BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit()
  spec.csharp:
  - uid: BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit
    name: Commit
    href: BallastLaneBoard.Application.Abstractions.IUnitOfWork.html#BallastLaneBoard_Application_Abstractions_IUnitOfWork_Commit
  - name: (
  - name: )
  spec.vb:
  - uid: BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit
    name: Commit
    href: BallastLaneBoard.Application.Abstractions.IUnitOfWork.html#BallastLaneBoard_Application_Abstractions_IUnitOfWork_Commit
  - name: (
  - name: )
- uid: BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit(System.Threading.CancellationToken)
  commentId: M:BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit(System.Threading.CancellationToken)
  parent: BallastLaneBoard.Application.Abstractions.IUnitOfWork
  isExternal: true
  href: BallastLaneBoard.Application.Abstractions.IUnitOfWork.html#BallastLaneBoard_Application_Abstractions_IUnitOfWork_Commit_System_Threading_CancellationToken_
  name: Commit(CancellationToken)
  nameWithType: IUnitOfWork.Commit(CancellationToken)
  fullName: BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit(System.Threading.CancellationToken)
  spec.csharp:
  - uid: BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit(System.Threading.CancellationToken)
    name: Commit
    href: BallastLaneBoard.Application.Abstractions.IUnitOfWork.html#BallastLaneBoard_Application_Abstractions_IUnitOfWork_Commit_System_Threading_CancellationToken_
  - name: (
  - uid: System.Threading.CancellationToken
    name: CancellationToken
    isExternal: true
  - name: )
  spec.vb:
  - uid: BallastLaneBoard.Application.Abstractions.IUnitOfWork.Commit(System.Threading.CancellationToken)
    name: Commit
    href: BallastLaneBoard.Application.Abstractions.IUnitOfWork.html#BallastLaneBoard_Application_Abstractions_IUnitOfWork_Commit_System_Threading_CancellationToken_
  - name: (
  - uid: System.Threading.CancellationToken
    name: CancellationToken
    isExternal: true
  - name: )
- uid: BallastLaneBoard.Application.Abstractions.IUnitOfWork
  commentId: T:BallastLaneBoard.Application.Abstractions.IUnitOfWork
  parent: BallastLaneBoard.Application.Abstractions
  href: BallastLaneBoard.Application.Abstractions.IUnitOfWork.html
  name: IUnitOfWork
  nameWithType: IUnitOfWork
  fullName: BallastLaneBoard.Application.Abstractions.IUnitOfWork
- uid: BallastLaneBoard.Application.Abstractions
  commentId: N:BallastLaneBoard.Application.Abstractions
  href: BallastLaneBoard.html
  name: BallastLaneBoard.Application.Abstractions
  nameWithType: BallastLaneBoard.Application.Abstractions
  fullName: BallastLaneBoard.Application.Abstractions
  spec.csharp:
  - uid: BallastLaneBoard
    name: BallastLaneBoard
    href: BallastLaneBoard.html
  - name: .
  - uid: BallastLaneBoard.Application
    name: Application
    href: BallastLaneBoard.Application.html
  - name: .
  - uid: BallastLaneBoard.Application.Abstractions
    name: Abstractions
    href: BallastLaneBoard.Application.Abstractions.html
  spec.vb:
  - uid: BallastLaneBoard
    name: BallastLaneBoard
    href: BallastLaneBoard.html
  - name: .
  - uid: BallastLaneBoard.Application
    name: Application
    href: BallastLaneBoard.Application.html
  - name: .
  - uid: BallastLaneBoard.Application.Abstractions
    name: Abstractions
    href: BallastLaneBoard.Application.Abstractions.html
- uid: BallastLaneBoard.Application.TaskManagement.ITaskUoW.Tasks*
  commentId: Overload:BallastLaneBoard.Application.TaskManagement.ITaskUoW.Tasks
  href: BallastLaneBoard.Application.TaskManagement.ITaskUoW.html#BallastLaneBoard_Application_TaskManagement_ITaskUoW_Tasks
  name: Tasks
  nameWithType: ITaskUoW.Tasks
  fullName: BallastLaneBoard.Application.TaskManagement.ITaskUoW.Tasks
- uid: BallastLaneBoard.Application.Abstractions.IRepository{BallastLaneBoard.Domain.TaskManagement.TaskItem}
  commentId: T:BallastLaneBoard.Application.Abstractions.IRepository{BallastLaneBoard.Domain.TaskManagement.TaskItem}
  parent: BallastLaneBoard.Application.Abstractions
  definition: BallastLaneBoard.Application.Abstractions.IRepository`1
  href: BallastLaneBoard.Application.Abstractions.IRepository-1.html
  name: IRepository<TaskItem>
  nameWithType: IRepository<TaskItem>
  fullName: BallastLaneBoard.Application.Abstractions.IRepository<BallastLaneBoard.Domain.TaskManagement.TaskItem>
  nameWithType.vb: IRepository(Of TaskItem)
  fullName.vb: BallastLaneBoard.Application.Abstractions.IRepository(Of BallastLaneBoard.Domain.TaskManagement.TaskItem)
  name.vb: IRepository(Of TaskItem)
  spec.csharp:
  - uid: BallastLaneBoard.Application.Abstractions.IRepository`1
    name: IRepository
    href: BallastLaneBoard.Application.Abstractions.IRepository-1.html
  - name: <
  - uid: BallastLaneBoard.Domain.TaskManagement.TaskItem
    name: TaskItem
    href: BallastLaneBoard.Domain.TaskManagement.TaskItem.html
  - name: '>'
  spec.vb:
  - uid: BallastLaneBoard.Application.Abstractions.IRepository`1
    name: IRepository
    href: BallastLaneBoard.Application.Abstractions.IRepository-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: BallastLaneBoard.Domain.TaskManagement.TaskItem
    name: TaskItem
    href: BallastLaneBoard.Domain.TaskManagement.TaskItem.html
  - name: )
- uid: BallastLaneBoard.Application.Abstractions.IRepository`1
  commentId: T:BallastLaneBoard.Application.Abstractions.IRepository`1
  href: BallastLaneBoard.Application.Abstractions.IRepository-1.html
  name: IRepository<TEntity>
  nameWithType: IRepository<TEntity>
  fullName: BallastLaneBoard.Application.Abstractions.IRepository<TEntity>
  nameWithType.vb: IRepository(Of TEntity)
  fullName.vb: BallastLaneBoard.Application.Abstractions.IRepository(Of TEntity)
  name.vb: IRepository(Of TEntity)
  spec.csharp:
  - uid: BallastLaneBoard.Application.Abstractions.IRepository`1
    name: IRepository
    href: BallastLaneBoard.Application.Abstractions.IRepository-1.html
  - name: <
  - name: TEntity
  - name: '>'
  spec.vb:
  - uid: BallastLaneBoard.Application.Abstractions.IRepository`1
    name: IRepository
    href: BallastLaneBoard.Application.Abstractions.IRepository-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
